# Site settings
title: Technoskald
name: Technoskald
email: krmaxwell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        So much hacking, so little time
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://technoskald.github.io" # the base hostname & protocol for your site
twitter_username: kylemaxwell
github_username:  technoskald

# Build settings
markdown: kramdown

# Octopress migration
permalink: /:year/:month/:day/:title/

# Solarized
paginate: 10
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
